### ISSUE TITLE
Single inputs

### ISSUE THREAD

**Issue by smooJitter** [Fundflow/apollo-redux-form#46]
How would I handle single input queries.

```
mutation User($input: UserInput!){
   updateUser(input: {
       id
       name
       profile
    })
}

```
in other words, the mutation accepts an object as a single argument.

**Comment by mstn** [comment]
Hi, thanks for your question. 

A form is created with the fields of `UserInput` object (e.g. 'input.name').

You can find an example here https://github.com/Fundflow/apollo-redux-form/blob/master/stories/MonetaryAmount.js

I close the issue since I think I answered your question. Please feel free to open it again if I did not.
